name: CI Build Windows

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-msvc-release:
    runs-on: windows-latest
    steps:
      - name: Activate VS prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.2

      - name: Source checkout
        uses: actions/checkout@v2

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure
        run: cmake -B build -G Ninja

      - name: Build
        run: cmake --build build -- -k0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: MSVC Release build
          path: |
            ${{github.workspace}}/build/skynet_plot.exe
            ${{github.workspace}}/build/skynet_plot_k34.exe

  upload-release-artifacts:
    runs-on: ubuntu-latest
    needs:
      - build-msvc-release
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: MSVC Release build
          path: ${{github.workspace}}/build/

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        id: tag-name
        run: |
          echo "::set-output name=TAG_NAME::$(echo ${{ github.ref }} | cut -d'/' -f 3)"

      - name: Get Release ID
        if: startsWith(github.ref, 'refs/tags/')
        id: release-id
        run: |
          echo ::set-output name=RELEASE_ID::$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag-name.outputs.TAG_NAME }} | jq '.id')

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: $(file -b --mime-type ${{github.workspace}}/build/skynet_plot.exe)" \
            --data-binary @${{github.workspace}}/build/skynet_plot.exe \
            https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.release-id.outputs.RELEASE_ID }}/assets?name=skynet_plot-${{ steps.tag-name.outputs.TAG_NAME }}.exe

          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: $(file -b --mime-type ${{github.workspace}}/build/skynet_plot_k34.exe)" \
            --data-binary @${{github.workspace}}/build/skynet_plot_k34.exe \
            https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.release-id.outputs.RELEASE_ID }}/assets?name=skynet_plot_k34-${{ steps.tag-name.outputs.TAG_NAME }}.exe
